/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the assistance detail information
 */
public class AssistanceDetail {
  /**
   * Indicates the status of the assistance.   * &#x60;ACTIVE&#x60; -  Indicates that status for recurrent payment is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is deactivated. 
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

  } 
  @Override
  public String getId() {
    return id;
  }
  @Override
  public void setId(String id) {
    this.id = id;
  }
  @Override
  public java.util.Date getOperationDate() {
    return operationDate;
  }
  @Override
  public void setOperationDate(java.util.Date operationDate) {
    this.operationDate = operationDate;
  }


}
