package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Data implements java.io.Serializable {

	static final long serialVersionUID = 11L;

	private java.lang.String contractkey;
	private java.lang.String activationdate;
	private java.lang.String type;
	private java.lang.String status;
	private java.lang.String lastevaluationdate;
	private java.lang.String cutofdate;
	private com.bancosantander.likeu.model.CardDetail card;
/**
 * Constructor de la clase
 */
	public Data() {
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getContractkey() {
		return this.contractkey;
	}
	/**
 * Constructor de la clase
 */
	public void setContractkey(java.lang.String contractkey) {
		this.contractkey = contractkey;
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getActivationdate() {
		return this.activationdate;
	}
	/**
 * Constructor de la clase
 */
	public void setActivationdate(java.lang.String activationdate) {
		this.activationdate = activationdate;
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getType() {
		return this.type;
	}
	/**
 * Constructor de la clase
 */
	public void setType(java.lang.String type) {
		this.type = type;
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getStatus() {
		return this.status;
	}
	/**
 * Constructor de la clase
 */
	public void setStatus(java.lang.String status) {
		this.status = status;
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getLastevaluationdate() {
		return this.lastevaluationdate;
	}
	/**
 * Constructor de la clase
 */
	public void setLast_evaluation_date(java.lang.String lastevaluationdate) {
		this.lastevaluationdate = lastevaluationdate;
	}
	/**
 * Constructor de la clase
 */
	public java.lang.String getCutofdate() {
		return this.cutofdate;
	}
	/**
 * Constructor de la clase
 */
	public void setCut_of_date(java.lang.String cutofdate) {
		this.cutofdate = cutofdate;
	}
	/**
 * Constructor de la clase
 */
	public com.bancosantander.likeu.model.CardDetail getCard() {
		return this.card;
	}
	/**
 * Constructor de la clase
 */
	public void setCard(com.bancosantander.likeu.model.CardDetail card) {
		this.card = card;
	}
/**
 * Constructor de la clase
 */
	public Data(java.lang.String contractkey,
			java.lang.String activationdate, java.lang.String type,
			java.lang.String status, java.lang.String lastevaluationdate,
			java.lang.String cutofdate,
			com.bancosantander.likeu.model.CardDetail card) {
		this.contractkey = contractkey;
		this.activationdate = activationdate;
		this.type = type;
		this.status = status;
		this.last_evaluationdate = lastevaluationdate;
		this.cutofdate = cutofdate;
		this.card = card;
	}

}