/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.math.BigDecimal;
/**
 * Money Fields that represent money, must follow this structure: 
 */

public class Money {
  private BigDecimal amount = null;

  private String currencyCode = null;

	/**
	 * @return
	 */
  public BigDecimal getAmount() {
    return amount;
  }
/**
	 * @param BigDecimal
	 */
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }
	/**
	 * @return
	 */
  public String getCurrencyCode() {
    return currencyCode;
  }
/**
	 * @param String
	 */
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


}
